### ISSUE TITLE
[Request] Disable long press from space

### ISSUE THREAD

**Issue by MeiRos** [openboard-team/openboard#198]
New OpenBoard user here.
When entering login credentials my keyboard is open and I need to open my password vault (Bitwarden-rs) with fingerprint. The location for fingerprint is on the space bar. When using it, choose keyboard opens and that's really annoying.
So, ability to disable long press space to change keyboard would be awesome.

**Comment by sirius-c** [comment]
Also while trying to move the cursor with the swipe gesture on the space bar, the 'Change language' menu is sometimes opened accidentally, when not starting to swipe soon enough. 

Since there are multiple other ways to change the language, I would also like to be able to disable that space bar feature - or remove it altogether.

An alternative for the gesture problem might be to open the 'Change language' menu only on key release if no swipe occurred.

**Comment by szero** [comment]
Backing what @sirius-c said. The change language feature shouldn't be accessible through space long press altogether, or there could be option in settings to turn it on/off.
