### ISSUE TITLE
[ES] No suggestion when using opening exclamation/question mark

### ISSUE THREAD

**Issue by ElSebita** [openboard-team/openboard#667]
**Describe the bug**
In Spanish there are opening symbols to mark a question or an exclamation. "¿Dónde vas?"
After typing the opening mark, keyboard doesn't suggest any word. Tapping backspace activates the suggestion, though.

**To Reproduce**
1. Use Spanish
2. Tap an opening exclamation or question mark ¿ ¡
3. Start typing
4. There are no suggestions or corrections

**Expected behavior**
Whenever keyboard detects an opening mark in Spanish, suggestion should be active again since it's a grammar rule, not a special word.

**Screenshots**
![Screenshot_20220812-211804_GitHub.png](https://user-images.githubusercontent.com/7228356/184459529-1fd0f03d-9584-450d-a4d9-2b5c3550fb76.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9 (cepheus)
 - OS: Android 12.1

**Additional context**
Nothing to note

**Comment by Helium314** [comment]
I only did a very quick test, and adding `¿¡` to `symbols_word_connectors` for `es` appears to help.
But lacking Spanish language skills I can't test properly and tell whether it may have unintended side effects, as `isWordConnector` is checked in many places.

**Comment by ElSebita** [comment]
Tell me what to do, what tests you need, and I can do it.

**Comment by Helium314** [comment]
All I did was adding a file `donottranslate-config-spacing-and-punctuations.xml` to `app/src/main/res/values-es` with content

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
    <string name="symbols_word_connectors">\'-¡¿</string>
</resources>
```
Can you compile the app yourself? If not I can upload an APK.

**Comment by ElSebita** [comment]
I never compiled an APK before 😅

**Comment by Helium314** [comment]
Hm, I did some more test and noticed that if you tap the word after it's written, OpenBoard with my modification will show `¿Donde` as center suggestion, while it should obviously be `Donde`...
So only while you write it looks good, but my initial approach definitely was not a solution.

Anyway, when adding `¿¡` to `symbols_word_separators` instead of `symbols_word_connectors` it appears to work.

APK (zipped because GitHub doesn't allow attaching APK): [openboard_es_fix.zip](https://github.com/openboard-team/openboard/files/9409139/openboard_es_fix.zip)
Note that you will have to uninstall OpenBoard, because the signing key does not match. If possible you should back up the original app before you try this version, so you don't lose your settings and typed word history (personal dictionary is safe).

**Comment by ElSebita** [comment]
Working like a charm so far
